export { default as Home } from "./home";
export { default as About } from "./about-us";
export { default as Studio } from "./studios";
export { default as Contact } from "./contact-us";
export { default as Cameras } from "./camera";
export { default as DescCamera } from "./desc-camera";
export { default as VideoProduction } from "./video-productions";
export { default as AerialPhoto } from "./aerial-photography";
export { default as NotFound } from "./not-found";
